### ISSUE TITLE
Implement production logging

### ISSUE THREAD

**Issue by benwilhelm** [open-city/recycling#100]
Heroku has a number of log processing/notification add-ons available. We should implement on of them.

**Comment by alexkahn** [comment]
[Logentries](https://addons.heroku.com/logentries?utm_campaign=search&utm_medium=dashboard&utm_source=addons#tryit) looks like a good one to me, I'm also thinking [Raygun](https://addons.heroku.com/raygun?utm_campaign=search&utm_medium=dashboard&utm_source=addons).

**Comment by alexkahn** [comment]
Just went with logentries.
