### ISSUE TITLE
Error showing on Contact Form

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#103]
There is an "Invalid domain for site key" error showing on the contact form. 
![screen shot 2015-01-26 at 11 01 55 am](https://cloud.githubusercontent.com/assets/6717960/5904148/2162c4bc-a54c-11e4-9660-533dcb61a660.png)

**Comment by benwilhelm** [comment]
Sorry about that. Should be fixed now

**Comment by alexkahn** [comment]
Fixed, good to go.
