### ISSUE TITLE
Error in contact form still showing in Chrome

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#105]
Hiya, I checked Chrome and the error is still showing. Firefox and Safari are fine, though. Happy softlaunch day!

![screen shot 2015-01-27 at 9 50 59 am](https://cloud.githubusercontent.com/assets/6717960/5921558/725c0ce8-a60a-11e4-8801-1a994c138ba3.png)

**Comment by alexkahn** [comment]
Try doing a hard refresh (Ctrl(or Cmd) + Shift + r), you may be displaying a cached version. Chrome isn't displaying the captcha properly for me.

**Comment by matiaskitty** [comment]
Yep, even with a hard refresh the error is still displaying.

**Comment by alexkahn** [comment]
Is that happening when you run the app locally or from the domain?

**Comment by matiaskitty** [comment]
from the domain

**Comment by alexkahn** [comment]
![screen shot 2015-01-27 at 1 12 27 pm](https://cloud.githubusercontent.com/assets/4401271/5925052/90664386-a626-11e4-853a-c1241caa3f87.png)

This is what I am getting on Chrome.

**Comment by matiaskitty** [comment]
Yep, now I'm getting the same thing. Closing the issue.
