### ISSUE TITLE
map tiles not loading

### ISSUE THREAD

**Issue by derekeder** [open-city/recycling#109]
Looks like your map tiles aren't loading. My guess is your MapBox account has hit its limit for monthly views.

Options:

* pay mapbox ($5/mo should do it)
* switch to OSM tiles: `http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png`

![screen shot 2015-01-29 at 10 51 41 am](https://cloud.githubusercontent.com/assets/919583/5961876/2487a454-a7a5-11e4-9b8b-abc1e308d0e6.png)

**Comment by benwilhelm** [comment]
Thanks Derek. All fixed.
