### ISSUE TITLE
All address entries getting a 404 error

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#110]
per a user:

I’m afraid it doesn’t work with any address I try — looks like the geocode.json url is 404.

**Comment by derekeder** [comment]
Looks like the Google Geocoder has hit the max number of requests: 2,500/day ((source)[https://developers.google.com/maps/documentation/geocoding/#Limits])

The code that runs the geocoder looks to be running on the server side: https://github.com/open-city/recycling/blob/45fa8988484bc768f600e767314c652f29730d8b/routes/geocode.js

### Suggested fix
Google measures usage by IP address. Move the geocoding logic to client side code so every individual user will be able to get 2,500 requests.

**Comment by benwilhelm** [comment]
All fixed

**Comment by matiaskitty** [comment]
Awesome. Thanks.
