### ISSUE TITLE
add a section for press coverage?

### ISSUE THREAD

**Issue by derekeder** [open-city/recycling#111]
You guys got some press!

http://www.dnainfo.com/chicago/20150130/river-north/website-wants-know-if-your-apartment-building-doesnt-have-recycling

I find it useful to collect and link to this press coverage, perhaps on the about page. It gives visitors some additional context as to the impact you've had. Plus, its a nice place to keep track of it for yourselves ;)

**Comment by matiaskitty** [comment]
Maybe we could take out "Learn About Recycling in Chicago" since it is also
on the "Get Involved" page and replace it with press. What do you think Ben
and Alex?

**Comment by alexkahn** [comment]
We can put in a press section. @benwilhelm thoughts?

**Comment by benwilhelm** [comment]
I think claire's idea is a good one. Let's replace "learn about recycling" with the press block on the about page. Claire, can you provide a list of the press that you want to feature?

**Comment by matiaskitty** [comment]
[Website Holds Building Owners Accountable on Recycling] (https://soundcloud.com/techshift/website-holds-building-owners-accountable-on-recycling) (Audio)
Claire Micklin interviewed by Justin Kaufmann on *WBEZ Afternoon Shift* | February 2, 2015

[My Building Doesn't Recycle: An Interview with App Creator Claire Micklin] (http://www.mikenowak.net/podcasts/?p=episode&name=2015-02-01_2015-02-01_2015-01-31_claire_micklin.mp3) (Audio)
Claire Micklin interviewed by Mike Nowak on *The Mike Nowak Show* | February 1, 2015

[Does Your Apartment Have Recycling? If Not, It's Illegal] (http://www.dnainfo.com/chicago/20150130/river-north/website-wants-know-if-your-apartment-building-doesnt-have-recycling)
by Tanveer Ali in *DNAinfo Chicago* | January 30, 2015

**Comment by benwilhelm** [comment]
Done.  If it looks good you claire, go ahead and close this issue:

http://mybuildingdoesntrecycle.com/about

**Comment by matiaskitty** [comment]
Looks good! Two things:

1. Label the section Press
2. Bold the names of the media outlets

**Comment by alexkahn** [comment]
Does this do what you want?
![screen shot 2015-02-06 at 2 00 50 pm](https://cloud.githubusercontent.com/assets/4401271/6086585/b22e71b6-ae08-11e4-94ca-cdb71c28c78a.png)

see: https://github.com/open-city/recycling/pull/116

**Comment by matiaskitty** [comment]
that looks great! thanks.
