### ISSUE TITLE
Add link to the Github repo?

### ISSUE THREAD

**Issue by shua123** [open-city/recycling#113]
Maybe on About page.

**Comment by alexkahn** [comment]
Included in [PR 112](https://github.com/open-city/recycling/pull/112)

**Comment by benwilhelm** [comment]
What do you think about moving this into the footer?

**Comment by alexkahn** [comment]
I though about it. My reasoning was I thought it should be prominent (like the Fork ribbons). It totally makes sense to have it in the footer but I think it's kind of like hiding in the fine print. We're proudly open. It could easily go in the footer but I just want to make sure it's noticeable.

On February 3, 2015 8:56:48 PM CST, Ben <notifications@github.com> wrote:
>What do you think about moving this into the footer?
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/open-city/recycling/issues/113#issuecomment-72781641

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by matiaskitty** [comment]
sounds good to me.

**Comment by alexkahn** [comment]
So in the footer but similar to what's on there?

**Comment by matiaskitty** [comment]
We could do the github symbol and "pull requests welcome "

**Comment by alexkahn** [comment]
My vote is for the canonical "Fork us on GitHub" but it seems we've reached consensus on putting it in the footer.

**Comment by alexkahn** [comment]
Here's a screenshot:
![screen shot 2015-02-06 at 2 10 48 pm](https://cloud.githubusercontent.com/assets/4401271/6086774/0654548a-ae0a-11e4-9534-08884a5aa4dc.png)

See https://github.com/open-city/recycling/pull/117
