### ISSUE TITLE
Add Report Count to Map

### ISSUE THREAD

**Issue by benwilhelm** [open-city/recycling#114]
In the lower left corner of the map, similar to the copyright notice on the right, add a notice that says "[x] reports at [y] buildings", which are simple counts of the `reports` and `locations` collections, respectively

**Comment by alexkahn** [comment]
Questions: will that hit the DB every time? It's not a big deal if it does but if memcached stores the value of the call it won't be an up-to-date number. Happy to do this, just want to clarify the interaction with memcached.

**Comment by benwilhelm** [comment]
for the locations count, you can just count the number of pins already on the map. For the reports count, you can request from /reports.json, and count the results you get.  You'll need to add a memcached lookup in the reports route, similar to locations.index.  Basically, you check to see if there's already an entry in memcached for all of the reports. Use the key `reports.all` to be consistent with what I did in the locations routes. If the value exists in memcached, you serve that. If there's not, you fetch from the database, set the value in memcached, and serve it.  Also, you'll need to invalidate that value when new reports are created. You can see at the end of the reports.create method, there's a line

    cache.delete('locations.all');

Just add an identical call for `reports.all`.  Let me know if anything I've said or done doesn't make sense.

**Comment by alexkahn** [comment]
Hey, started some boilerplate, let me know what you think:

https://gist.github.com/alexkahn/ef161a4a534d45490764

**Comment by alexkahn** [comment]
I've got a [PR](https://github.com/open-city/recycling/pull/122) up for this issue.

**Comment by matiaskitty** [comment]
Hi Alex,
Can I help with the pull request? Ben is on vacation.

Best,
Claire
