### ISSUE TITLE
Put plug in for Smart Chicago Collaborative on About page

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#115]
After last sentence of first paragraph in About page, add this:

Upgraded Mapbox and Google API licenses were generously donated by [Smart Chicago Collaborative](http://www.smartchicagocollaborative.org/). The Smart Chicago Collaborative offers [free developer resources] (http://www.smartchicagocollaborative.org/work/ecosystem/developer-resources/) for qualifying civic innovation projects.

**Comment by benwilhelm** [comment]
Plugged:

http://mybuildingdoesntrecycle.com/about

Close it if you dig it.

**Comment by matiaskitty** [comment]
Closed, yo.
