### ISSUE TITLE
Facebook share button on Get Involved page

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#118]
Morning!

I noticed that the Facebook share button reads "Log In" [ see screenshot ] when I am not logged in to my Facebook account. Is that what is supposed to happen? 
![screen shot 2015-02-08 at 9 35 24 am](https://cloud.githubusercontent.com/assets/6717960/6097155/bbe6119e-af77-11e4-88a4-2ca54f14abfa.png)

**Comment by alexkahn** [comment]
I think that is supposed to happen but it may be that we can do something about it.

**Comment by benwilhelm** [comment]
I'm not seeing this. I tried logging out of facebook and opening an anonymous window, but it still shows me the normal share button.  Are you all still seeing it?

**Comment by alexkahn** [comment]
When I am not in an anonymous browser, logged into FB or not I can't see the share button at all. Strange but I would consider this an edge case, don't know what we can really do about it. Closing the issue assuming most everyone can see the button or can figure out how to share something on FB.
