### ISSUE TITLE
Remove report for 1401 W. Gregory in Mount Prospect

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#120]
There is a report for 1401 W. Gregory in Mount Prospect that somehow slipped through. I think the reporter 
![screen shot 2015-02-12 at 4 17 45 pm](https://cloud.githubusercontent.com/assets/6717960/6178332/8c6f8dfa-b2d3-11e4-833a-a0a2f2b2d77e.png)

If a user just types in 1401 W. Gregory the map defaults to the 1401 W. Gregory in Mt. Prospect. If I type in 1401 W. Gregory, Chicago, the map goes to the correct place. ¯\_(ツ)_/¯

**Comment by benwilhelm** [comment]
Done
