### ISSUE TITLE
Remove accidental report

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#121]
Someone I work with told me they made an accidental report today (Feb 12) at 10:49am from ip address: 10.150.22.246.

**Comment by benwilhelm** [comment]
What's the building address?  We don't attach IPs to building reports

**Comment by matiaskitty** [comment]
The person who submitted actually know which bldg she submitted. She was exploring the pins and accidentally submitted.

**Comment by benwilhelm** [comment]
Not much to be done then.
