### ISSUE TITLE
Take out sentence in About page

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#127]
Take out the following sentence, on the About page, under "What will you do with the data?"

Once there are a significant number of reports our group can begin to use these reports to show elected officials a rough estimate of how many multi-unit buildings are not providing recycling services.

**Comment by alexkahn** [comment]
Made a pull request here:
https://github.com/open-city/recycling/pull/128

**Comment by alexkahn** [comment]
Merged and deployed.
