### ISSUE TITLE
Updates: Press page, About page

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#133]
Hi Alex,
I have some updates for the site. I created a Press page and changed the About page a bit. I highlighted all changed areas in yellow.

Updates are the following:

Press page 
All content is new. 
http://d6n26m.axshare.com/#p=press

About page
- I put a "Take further action" sentence at the bottom of the page. 
- I updated the Press sidebar with the latest articles. 
- I put a link to the Press page below the latest articles. 
http://d6n26m.axshare.com/#p=press

Thanks much and let me know if you have any questions.

**Comment by matiaskitty** [comment]
oh, also, I made Press a navigation item.

**Comment by alexkahn** [comment]
Accepted on 963f022
