### ISSUE TITLE
Logentries: Memory Quota Exceeded

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#144]
Now the LogEntries alerts are continually coming in. According to the LogEntries dashboard this issue is Critical. 

![screen shot 2015-10-14 at 9 36 45 pm](https://cloud.githubusercontent.com/assets/6717960/10503465/dc4fd7dc-72bb-11e5-85d4-0285a9a6e2f6.png)

**Comment by evz** [comment]
@matiaskitty Wow, I'd be honored to help out here but I'm not sure I have access to that app. if this wasn't assigned to me accidentally, just point me in the right direction and I'll see what I can figure out.

**Comment by benwilhelm** [comment]
@alexkahn, do you have a minute to look at this? The app is using more memory than the heroku dyno allows and is starting to swap. 

https://devcenter.heroku.com/articles/error-codes#r14-memory-quota-exceeded

Not the end of the world for the moment as long as we're not expecting a traffic spike. My first though would be that serializing the entire map's result set to save or retrieve it from memcached is causing the overage. I don't think I'll have time to troubleshoot this till the weekend. It might just mean upping to a paid dyno, but we probably want to start returning the results in smaller sets regardless.

**Comment by alexkahn** [comment]
I cranked up the app by adding a small cluster implementation for adding multiple processes. We did actually bump up to a paid (hobby) dyno but I think it might be a good idea to either upgrade again (for more memory) or off-load the static assets to a CDN or similar.

**Comment by alexkahn** [comment]
@evz We would love to have you - feel free to submit a Pull Request any time. I don't think this was an intentional assignment but if you've got some Node.js or client side JavaScript chops, feel free to make a contribution!
