### ISSUE TITLE
Add proper sharing links for twitter and facebook

### ISSUE THREAD

**Issue by benwilhelm** [open-city/recycling#53]
The twitter and facebook buttons on the get-involved page and the report submitted page are not currently functional.

**Comment by matiaskitty** [comment]
We don't currently have a Facebook or Twitter page / account for the project, but the Facebook and Twitter buttons are just for people to share our site on on Facebook or Twitter.

**Comment by alexkahn** [comment]
To make those buttons Share, we need to have Facebook and Twitter Credentials for API access to make the posts. I can just make some developer accounts we can use.

**Comment by matiaskitty** [comment]
okay, cool. Guess I didn't understand all it takes to make teh buttons
functional.

**Comment by alexkahn** [comment]
I'm going to use the gmail account we have to set everything up, @matiaskitty @benwilhelm, whoever has the credentials to sign in to that accout, might you do the account confirmations? Thanks!

**Comment by benwilhelm** [comment]
yes, either of us can do it.  let us know when you've created the accounts and one of us will verify.  And we can give you the credentials on tuesday.

**Comment by matiaskitty** [comment]
Hi Alex, 
Can you make the sharing links work today? We are getting lots of hits on the site!

**Comment by alexkahn** [comment]
Yeah, I've been having trouble setting up the Facebook sharing but I'll work on Twitter and at least get that running.

**Comment by benwilhelm** [comment]
I see you've pushed your branch. I can take a look at the facebook integration when I get home tonight.

**Comment by benwilhelm** [comment]
I've added the simple embedded version of twitter and facebook buttons, which don't require a developer account:

https://about.twitter.com/resources/buttons#tweet
https://developers.facebook.com/docs/plugins/share-button

**Comment by alexkahn** [comment]
I'm not seeing a Facebook button on the get involved page. Working on it.

**Comment by matiaskitty** [comment]
It takes a while for the fb button to load

**Comment by alexkahn** [comment]
I've done some debugging and it looks like the request to Facebook is getting a 307 (internal redirect) and not getting a response. The button hasn't rendered for me yet.

**Comment by benwilhelm** [comment]
Renders fine for me. I wouldn't make yourself crazy over it.

**Comment by alexkahn** [comment]
Fair enough...
