### ISSUE TITLE
Chicago recycling policy research

### ISSUE THREAD

**Issue by derekeder** [open-city/recycling#6]
It may be useful for this project to read what the City and others have already written about recycling in 5+ unit buildings. 

### City resources
It appears that the City has a policy in place for applying to get recycling multi-unit buildings. One feature of the app could be pointing people to these resources (or simplifying the process)

* [Recycling for Multi-Unit Residential Buildings](http://www.cityofchicago.org/city/en/depts/streets/supp_info/recycling1/recycling_multi-unitresidentialbuildings.html)
* [Resources and Frequently Asked Questions for Multi-Unit Recycling](http://www.cityofchicago.org/city/en/depts/streets/supp_info/recycling1/resources_and_frequentlyaskedquestionsformulti-unitrecycling.html)
* [Multi­Unit Residential Recycling Plan and Waste Generation and Recyclable Collection Worksheet](http://www.cityofchicago.org/content/dam/city/depts/streets/supp_info/Recycling/Recycling%20PDFdocs%202013/RecyclingPlan_WasteGeneration_final0213.pdf)
* [Source-Separated Recycling Service Providers](http://www.cityofchicago.org/content/dam/city/depts/streets/supp_info/Recycling/Recycling%20PDFdocs%202013/VendorMatrix1.pdf)
* [Multi-unit Residential Recycling 5 Step Process](http://www.cityofchicago.org/city/en/depts/streets/supp_info/recycling1/muti-unit_residentialrecycling5stepprocess.html)

Has anyone tried reaching out to Recycling & Compost Collection at Streets and Sanitation at the City? 
StreetsAndSan@cityofchicago.org
(312) 744-4611 
121 N. LaSalle St. Rm. 1107

### Chicago Recycling Ordinance
* [Chicago High Density Residential and Commercial Source Reduction and Recycling Ordinance](http://www.luc.edu/media/lucedu/sustainability-new/pdfs/REcycling%20Ordinance%20Chicago%2011%20%205.pdf)
* [Recycling:   High‐Density  Residential  &  Commercial  Properties ](http://www.chicagorecycling.org/High-Density_Res_&_Commercial_Recycling_WEB_04032011.pdf) Chicago  Recycling  Coalition
* [Why Can't Chicago Recycle? ](http://www.chicagoreader.com/chicago/chicago-recycling-blue-carts-service/Content?oid=2135422) Chicago Reader

**Comment by benwilhelm** [comment]
In the interest of housekeeping, do you mind if I close this issue, Claire?

**Comment by matiaskitty** [comment]
Not at all. Thanks for attending to all this!
