### ISSUE TITLE
Create contact form

### ISSUE THREAD

**Issue by benwilhelm** [open-city/recycling#60]
Possibly use mailchimp or something to send emails. If so, let's look into integrating the mailing list signup with it.

**Comment by alexkahn** [comment]
Got this in the works, just wanted to take care of the rest first.

**Comment by benwilhelm** [comment]
If you haven't already looked into a front-end validation library, I would suggest checking out [parsley.js](http://parsleyjs.org/)

**Comment by benwilhelm** [comment]
I configured this to use mandrill and deployed to production. Give it a spin and let me know if I missed anything.
