### ISSUE TITLE
Add footer 

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#61]
This app was created by Claire Micklin (clairemicklin.com), Ben Wilhelm (Ben's github), and Alex Kahn (Alex's github) at Open Government Hack Night (http://opengovhacknight.org/), a project of Open City (http://opencityapps.org/).

Do we need copyright information? 

Add a Send Us Feedback or Contact Us link to contact form?

**Comment by matiaskitty** [comment]
Okay, I wireframed a footer, which you can see here (you may need to scroll): http://i785tr.axshare.com/#p=home

It sounds like the MIT license is linked to in the root files and does not directly show up in the footer. Is that right?

**Comment by alexkahn** [comment]
Fixed with 7dd7ecfa71037ac0ec144bab79f9c48460b7d0e8
