### ISSUE TITLE
Get Involved - Add Sample Letter to Alderman

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#66]
On the Get Involved page, after the "Email or call your alderman" paragraph add the following new sentence (in a new paragraph). 

Need ideas for what to write to your alderman? Below is a sample letter that you can copy.

Below that sentence add a button / header that can be clicked to toggle viewing the entire letter or hiding it again. See http://i785tr.axshare.com/get_involved.html

Let me know if the programming is too heavy to do the display / hide accordion button thing. We could just display the entire letter. That will just push other content down further.

**Comment by alexkahn** [comment]
Added with 68751d5dd2a090d67fc3321e85c9ad385d5a92ee
