### ISSUE TITLE
New text for Confirmation and thank you page 

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#68]
Confirmation and thank you page follows this wireframe:
http://i785tr.axshare.com/#p=confirmation_and_thank_you

Your Report Has Been Added to Our Registry!

Now Take the Next Steps:

Check out our Get Involved page and learn about further actions to take to promote multi-unit recycling in Chicago!

Share with friends and help spread the word that Chicagoans demand better recycling services!
[Facebook link]  [Twitter link]

Join our mailing list and get project updates

[Email list signup]

**Comment by alexkahn** [comment]
Changed with d81d9c434cdcff4c0aa000d5b243e37b9a2a3958
