### ISSUE TITLE
Mobile View - Make map smaller - show some of content below 

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#73]
Make the map smaller so that some of the content shows below it. Right now the interaction is a little awkward because the map resizes when you use a swipe gesture to scroll down. I've attached a screenshot. 

A good example for mobile map sizing is in this OpenPlans demo: https://openplans.org/demo/street-safety
![home_title](https://cloud.githubusercontent.com/assets/6717960/5698885/6b2559da-99de-11e4-9a82-96a630d2bdd1.PNG)

**Comment by benwilhelm** [comment]
@alexkahn, if you start on this one before me, talk to me first. Claire and I have talked about some UI changes to address this and #74

**Comment by benwilhelm** [comment]
@matiaskitty take a look now.  I made the map about half height in the mobile view, with a fullscreen option in the upper right.

**Comment by matiaskitty** [comment]
Hi Ben,

The mobile view is looking really great! I like the map at half height. I
tested out the full screen option with a couple people and I think there is
less of a use case for a full screen map on mobile (or desktop). I think we
should go with the half-height map for now. I think it looks good and
functions really well.
