### ISSUE TITLE
Mobile view - Have map scroll up (not have fixed positioning)

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#74]
Right now in mobile map is maintaining a fixed position and content is scrolling under it. Remove fixed positioning and have it scroll. I have attached a screenshot of how it is now. 
![home_scrolled](https://cloud.githubusercontent.com/assets/6717960/5698928/b4e478b6-99df-11e4-95ff-d50d4fbd204f.PNG)

**Comment by benwilhelm** [comment]
May be moot with the fix to #73

**Comment by alexkahn** [comment]
Working on it....

**Comment by benwilhelm** [comment]
This should already be done. It was addressed with the fix to #73 (see my comment above). Are you still seeing the map in fixed position?

**Comment by benwilhelm** [comment]
@alexkahn, @matiaskitty - I'd like to close this issue.  Speak now or forever hold your piece...
