### ISSUE TITLE
Configure mailing list signup to use MailChimp

### ISSUE THREAD

**Issue by benwilhelm** [open-city/recycling#79]
Account exists on Mailchimp. Credentials should be configured as heroku environment vars

**Comment by benwilhelm** [comment]
Have this in progress. Working out some list-related kinks and should be able to deploy soonish.

**Comment by benwilhelm** [comment]
Alright, I think this is done. @matiaskitty and @alexkahn, want to give this a whirl and see if you can spot any issues? FYI, it takes a little while for new subscriptions to show up on the list, so after you submit you might need to wait a couple hours to verify it.

http://www.mybuildingdoesntrecycle.com/get-involved

**Comment by matiaskitty** [comment]
on my end it looks good. One very small thing I noticed is is that the in the confirmation email, the Go to the Website button is set to go to recycling.herokuapp.com instead of mybuildingdoesntrecycle.com

**Comment by benwilhelm** [comment]
Yeah, I tried to change that in the mailchimp preferences, but they require an office phone number when updating the contact info. Claire, can you take care of changing that?

**Comment by matiaskitty** [comment]
I took care of changing the website address to mybuildingdoesntrecycle.com
