### ISSUE TITLE
Confirmation page not showing after Add Report button clicked - Chrome

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#83]
The confirmation page is now showing when I click the Add Report button. This happens in Chrome. 

https://www.dropbox.com/s/837z07ot3g9hft6/Screenshot%202015-01-17%2017.51.31.png?dl=0
![screenshot 2015-01-17 18 02 14](https://cloud.githubusercontent.com/assets/6717960/5790857/6d842c3a-9e73-11e4-9126-08cebbafa684.png)

**Comment by matiaskitty** [comment]
happening in Firefox too.

**Comment by benwilhelm** [comment]
This is probably related to the caching i just added. I'll take a look today.

**Comment by benwilhelm** [comment]
Should be fixed now. @matiaskitty, please try making a report on a new location and also adding a report to an existing location. If all goes well, you can close this ticket.
