### ISSUE TITLE
Include footnote in About Page

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#84]
On the About page: 

Wireframe link: http://i785tr.axshare.com/#p=about

Include a footnote (which includes a superscript "1" on the Chicago High Density Residential and Commercial Source Reduction Act text, and the explanatory footnote below. 

The footnote explains why I chose to host the text of the ordinance in a google doc

**Comment by matiaskitty** [comment]
Here's the amlegal publishing link:
http://www.amlegal.com/nxt/gateway.dll/Illinois/chicago_il/title5housingandeconomicdevelopment/chapter5-12residentiallandlordsandtenant?f=templates$fn=default.htm$3.0$vid=amlegal:chicago_il

**Comment by matiaskitty** [comment]
Hi Ben,

I heard back from AmLegal and they said that you actually can link directly to chapters in the municipal code by clicking on the little yellow bookmark symbol by the chapter title. Does this link work any better than the other one or is it still bad link:
http://www.amlegal.com/nxt/gateway.dll/Illinois/chicago_il/title11utilitiesandenvironmentalprotecti/chapter11-5reductionandrecyclingprogram?f=templates$fn=default.htm$3.0$vid=amlegal:chicago_il$anc=JD_Ch.11-5

**Comment by benwilhelm** [comment]
That one didn't for some reason but I was able to get one that did, so I linked directly to the page instead of the footnote. 

http://mybuildingdoesntrecycle.com/about

If that works for you, go ahead and close this ticket.
