### ISSUE TITLE
Put links in footer 

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#85]
Link the following in the footer:

link to wireframes: http://i785tr.axshare.com/#p=home

Claire Micklin                                   clairemicklin.com
Ben Wilhelm                                    bwilhelm.com
Alex Kahn                                        https://github.com/alexkahn
Open Government Hack Night        http://opengovhacknight.org/
Open City                                        http://opencityapps.org/

**Comment by alexkahn** [comment]
On it.

**Comment by alexkahn** [comment]
Resolved with ceee5f8a452e1b1d047aef7475eabb41fcee372e
