### ISSUE TITLE
Non-existent address allowed to be submitted

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#87]
![fake_report_android 2](https://cloud.githubusercontent.com/assets/6717960/5808993/62523758-9ff9-11e4-8d61-c8b0ef17025e.jpg)

Tester was allowed to submit a fake address.

**Comment by benwilhelm** [comment]
@alexkahn, do you have time to tackle this one?

**Comment by matiaskitty** [comment]
I entered "Cauliflower" as an address and was also defaulted to Chgo Cook County.

**Comment by alexkahn** [comment]
Working on this now.

**Comment by alexkahn** [comment]
Ok, so I've managed to try and fix the problem but I want to make sure the choice of using the javascript ```alert()``` is right for this context. I'll submit the PR in a moment.

**Comment by alexkahn** [comment]
See [here](https://github.com/open-city/recycling/commit/cd40e9f34a42e1c508db07ef549160ce1b193b69)

**Comment by alexkahn** [comment]
Issue resolved with https://github.com/open-city/recycling/commit/a584cc1bbe329005f136af270c6764739e4948df
