### ISSUE TITLE
Load Testing

### ISSUE THREAD

**Issue by benwilhelm** [open-city/recycling#90]
Do some prior to release.

**Comment by alexkahn** [comment]
Are we trying to use a free-tier heroku box? I can run some jMeter tests or something...

**Comment by benwilhelm** [comment]
I'm going to try the loader.io heroku addon

**Comment by benwilhelm** [comment]
Alright, I ran some load tests using loader.io and the results were very good.  I maintained a steady load of 1000 GET requests to /locations.json over a minute, while simultaneously POSTing to /reports.json (thereby busting the cache with a new report) about twice per second, and we topped out at about 2s response time.

**Comment by matiaskitty** [comment]
thanks, Ben!
