### ISSUE TITLE
Favicon not showing up in browser tab

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#91]
Favicon is not showing up in browser tab (at least in Chrome. Google favicon is showing instead).

**Comment by benwilhelm** [comment]
Hm. Strange.  Try it now with a hard refresh (hold down shift while refreshing the page)

If that solves it, you can close this ticket.

**Comment by alexkahn** [comment]
I'm getting the favicon on my dev server... is the production branch not up to that point?

**Comment by benwilhelm** [comment]
It's showing up for me on my dev server and on production on multiple computers. @alexkahn, are you seeing it?

**Comment by matiaskitty** [comment]
Yep, hard refresh worked. Thanks!
