### ISSUE TITLE
Accepting reports outside of Chicago?

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#97]
I typed in a Kalamazoo, Michigan address and the app let me report it. How do we want to handle reports outside of Chicago?

**Comment by alexkahn** [comment]
I'd say geo-fence the response area based on the ordinance's jurisdiction. We can test coordinates as they come back from google within an area. Mongoose I think should be able to handle that with Mongo's geospatial querying correct?

**Comment by benwilhelm** [comment]
I think a simpler solution is to check the value of the "city" field in the
maps api response. If it's not chicago, use the same notification mechanism
to the user that we're using for non-existent addresses.

**Comment by benwilhelm** [comment]
I'm taking care of this one, unless you've already started it, @alexkahn?

**Comment by benwilhelm** [comment]
Done and deployed. Please check and close, @matiaskitty
